### ISSUE TITLE
Azure classic release "Pull Request Status" task: Unable to set action to Update

### ISSUE THREAD

**Issue by teuciont** [joachimdalen/azdevops-pull-request-utils#15]
Hi, as the title implies, in an Azure classic release, when using the **Pull Request Status** task, trying to choose _Update_ causes the screen to go blank. I've repro'd this across three different browsers on three different machines
![BlankScreen (1)](https://user-images.githubusercontent.com/15051149/185470105-c4d9234a-c328-47f3-b085-00418b807492.gif)
.

**Comment by joachimdalen** [comment]
Hi! 

Thank you for reporting. I do not have time to look into this today, but I will follow up during the weekend and see if I can figure out what is going on :)

**Comment by joachimdalen** [comment]
I can confirm this issue. It seems like DevOps is throwing an exception, but I have yet not identified why. I will look some more into it.

**Comment by joachimdalen** [comment]
Fixed, released and verified. Thank you for reporting the issue :smile:

**Comment by tyler-j-jackson** [comment]
Thank you!
