### ISSUE TITLE
Update PullRequestStatus only if the status is fulfilled

### ISSUE THREAD

**Issue by knoxi** [joachimdalen/azdevops-pull-request-utils#7]
We have an update PullRequestStatus task, which sets the integration tests status to the PR. In the pipeline the integration tests run in parallel.
Now we have the problem that the PullRequestStatus of the tests overwrite each other status.
We would now like to have a way to define when the update is effectively applied, in our case only when e.g. the current PullRequestStatus is set to 'pending or succeeded'.

If this is not possible, an alternative would be that the PullRequestStatus task also supports `get` as an action, so that we can read the status and implement our own decision logic based on it.

**Comment by knoxi** [comment]
Hi @joachimdalen 

This would be exactly the feature we need to solve our issue. It would be great if that was integrated.

**Comment by joachimdalen** [comment]
Great! I'll get that feature implemented fully and deployed within the next few days :)

**Comment by knoxi** [comment]
That sounds great! Thanks a lot for your effort.

**Comment by joachimdalen** [comment]
Hey @knoxi !

I just released this in `1.1.0`, would you give it a go and see if this resolves your troubles? Usage example can be found here: https://docs.devops-extensions.dev/docs/extensions/pull-request-utils/tasks/pull-request-status#conditionally-update-status

**Comment by knoxi** [comment]
Hi @joachimdalen 
I finally managed it to update and test our pipelines. Now it works as expected.
Many thanks for that fast extension of the task, great work!
